services:
  # 1. La Base de Datos
  db:
    image: postgres:17-alpine
    container_name: nexhub-db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - nexhub-db-data:/var/lib/postgresql/data

  # 2. El Backend (Java + Spring Boot)
  backend:
    build: ./backend
    container_name: nexhub-backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - "${PORT}:8080" # Mapea el puerto del .env al 8080 del container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}

volumes:
  nexhub-db-data: